# Generated by Django 6.0.2 on 2026-02-21 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('task_type', models.CharField(choices=[('examen', 'Examen'), ('quiz', 'Quiz'), ('taller', 'Taller'), ('proyecto', 'Proyecto'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('course', models.CharField(max_length=100)),
                ('due_date', models.DateTimeField(blank=True, help_text='Fecha y hora límite de entrega', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target_date', models.DateField(help_text='Fecha en la que el usuario planea hacer esta subtarea')),
                ('original_target_date', models.DateField(blank=True, help_text='Guarda la fecha original si se reprograma', null=True)),
                ('estimated_hours', models.FloatField(help_text='Duración estimada para sumar a la carga del día')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('done', 'Completada'), ('postponed', 'Pospuesta')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='api.task')),
            ],
            options={
                'ordering': ['target_date', 'status'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.FloatField(default=6, help_text='Número máximo de horas de estudio por día')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
