# Generated by Django 6.0.2 on 2026-02-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción adicional de la tarea', null=True),
        ),
    ]
