# Generated by Django 5.2.7 on 2026-02-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Indica si la tarea ya fue finalizada'),
        ),
    ]
