# Generated by Django 6.0.2 on 2026-02-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='Detalles adicionales sobre la tarea', null=True),
        ),
    ]
