# Generated by Django 6.0.2 on 2026-05-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='estimated_hours',
            field=models.FloatField(choices=[(0.25, '15 min'), (0.5, '30 min'), (0.75, '45 min'), (1.0, '1 hora'), (1.5, '1.5 horas'), (2.0, '2 horas'), (3.0, '3 horas')], help_text='Duración estimada para sumar a la carga del día'),
        ),
    ]
