# Generated by Django 6.0.2 on 2026-05-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_subtask_estimated_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_postponed',
            field=models.BooleanField(default=False, help_text='Indica si la fecha de la tarea fue pospuesta'),
        ),
    ]
